language: python
python: 2.7
sudo: false

cache:
    directories:
        - $HOME/.cache/pip

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pypy
    - TOX_ENV=docs
    - TOX_ENV=pep8

install:
    - pip install tox
    - wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2 -O `pwd`/../pypy.tar.bz2
    - tar -xf `pwd`/../pypy.tar.bz2 -C `pwd`/../
script:
    - ./.travis/run.sh
notifications:
    email: false
